# Generated by Django 4.2.3 on 2023-07-23 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=65)),
                ('cód', models.IntegerField()),
                ('SKU', models.CharField(max_length=65)),
                ('Vendas', models.IntegerField()),
                ('EstoqueTotal', models.IntegerField()),
                ('CustoTotal', models.DecimalField(decimal_places=2, max_digits=9)),
                ('RevendaTotal', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
