# Generated by Django 4.2.3 on 2023-07-25 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtos',
            old_name='cód',
            new_name='Cod',
        ),
    ]
