# Generated by Django 4.2.3 on 2023-07-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_rename_cód_produtos_cod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cod', models.IntegerField()),
                ('esta_pago', models.BooleanField(default=False)),
                ('Data', models.DateTimeField(auto_now_add=True)),
                ('Nome_cliente', models.CharField(max_length=65)),
                ('Preco_venda', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
