# Generated by Django 4.2.3 on 2023-07-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_vendas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendas',
            name='esta_pago',
        ),
        migrations.AddField(
            model_name='vendas',
            name='Situacao',
            field=models.CharField(default=True, max_length=65),
        ),
    ]
