# Generated by Django 4.2.3 on 2023-07-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_remove_vendas_esta_pago_vendas_situacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendas',
            name='Nome_cliente',
        ),
        migrations.AddField(
            model_name='vendas',
            name='Primeiro_nome_cliente',
            field=models.CharField(default=True, max_length=65),
        ),
        migrations.AddField(
            model_name='vendas',
            name='Sobrenome_nome_cliente',
            field=models.CharField(default=True, max_length=65),
        ),
    ]
