# Generated by Django 4.2.3 on 2023-07-27 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_remove_vendas_nome_cliente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendas',
            old_name='Primeiro_nome_cliente',
            new_name='Nome_cliente',
        ),
        migrations.RenameField(
            model_name='vendas',
            old_name='Preco_venda',
            new_name='Preco_da_venda',
        ),
        migrations.RenameField(
            model_name='vendas',
            old_name='Sobrenome_nome_cliente',
            new_name='Sobrenome_cliente',
        ),
    ]
